import {
  Activity,
  ArrowLeftRight,
  BadgeCheck,
  Bot,
  Box,
  BrickWall,
  BookOpen,
  BookOpenCheck,
  Building,
  Calculator as CalculatorIcon,
  Drill,
  Droplets,
  Fan,
  FileCheck2,
  FileText,
  Flame,
  Gauge,
  Hammer,
  Home,
  Layers,
  Map,
  Network,
  Paintbrush,
  Pickaxe,
  Replace,
  Ruler,
  ScanSearch,
  ShieldCheck,
  Shapes,
  Square,
  Table2,
  Thermometer,
  Triangle,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

import {
  calculatorCategories,
  type Calculator,
  type CategorySlug,
} from "@/lib/calculators";

export const iconRegistry: Record<string, LucideIcon> = {
  Activity,
  ArrowLeftRight,
  BadgeCheck,
  Bot,
  Box,
  BrickWall,
  BookOpen,
  BookOpenCheck,
  Building,
  Calculator: CalculatorIcon,
  Drill,
  Droplets,
  Fan,
  FileCheck2,
  FileText,
  Flame,
  Gauge,
  Hammer,
  Home,
  Layers,
  Map,
  Network,
  Paintbrush,
  Pickaxe,
  Replace,
  Ruler,
  ScanSearch,
  ShieldCheck,
  Shapes,
  Square,
  Table2,
  Thermometer,
  Triangle,
  Wind,
  Wrench,
  Zap,
};

const FALLBACK_CATEGORY_ICONS: Record<CategorySlug, LucideIcon> = {
  "energoefektyvnist-teplotekhnika": Thermometer,
  "ogorodzhuvalni-konstruktsiyi": BrickWall,
  pidlohy: Layers,
  "voloha-tochka-rosy": Droplets,
  "temperatura-poverkhni": Gauge,
  "teplova-inertsiya": Activity,
  "teplovi-mistky-fem": Network,
  povitropronyknist: Wind,
  konstruktsiyi: Triangle,
  zalizobeton: Building,
  armatura: Drill,
  beton: Box,
  "balky-plyty": Ruler,
  fundamenty: Home,
  ankeruvannya: Pickaxe,
  "dovidkovi-tablytsi": Table2,
  "normy-perevirky": ShieldCheck,
  normokontrol: ShieldCheck,
  "klas-naslidkiv": BadgeCheck,
  "perevirka-dbn": FileCheck2,
  "normatyvni-obgruntuvannya": BookOpenCheck,
  "ai-asystenty-z-norm": Bot,
  "inzhenerni-merezhi": Zap,
  elektryka: Zap,
  opalennya: Flame,
  ventylyatsiya: Fan,
  vodopostachannya: Droplets,
  enerhospozhyvannya: Gauge,
  "cad-gis-dani": Map,
  "dxf-geojson": Map,
  konvertery: Replace,
  heometriya: Shapes,
  "import-eksport": ArrowLeftRight,
  dovidnyky: BookOpen,
  "dovidnyk-beton": Box,
  "dovidnyk-armatura": Drill,
  materialy: Layers,
  "normatyvni-kharakterystyky": Table2,
  "ai-instrumenty": Bot,
  "asystenty-dbn": Bot,
  "asystenty-perevirky-rishen": ScanSearch,
  "asystenty-pidhotovky-poyasnen": FileText,
};

export function getCategoryIcon(slug: CategorySlug): LucideIcon {
  const category = calculatorCategories.find((entry) => entry.slug === slug);
  if (category?.icon && iconRegistry[category.icon]) {
    return iconRegistry[category.icon];
  }
  return FALLBACK_CATEGORY_ICONS[slug] ?? Box;
}

export function getCalculatorIcon(calculator: Calculator): LucideIcon {
  if (calculator.icon && iconRegistry[calculator.icon]) {
    return iconRegistry[calculator.icon];
  }
  return getCategoryIcon(calculator.mainCategory);
}
