export type SteelStructureSectionId = `a1-section-${string}`;
export type SteelStructureId = `a1-${string}`;
export type PurposeCategory = "А" | "Б" | "В";
export type StressCategory = "I" | "II" | "III";
export type Table51Profile = "default" | "p1" | "p2" | "p3" | "p4" | "p5" | "p6a" | "p6b" | "p7" | "p8" | "p9";
export type ProductType = "section" | "long" | "sheet" | "universal_plate" | "cold_formed";
export type SteelStructureSection = { id: SteelStructureSectionId; number: number; title: string };
export type SteelStructureCatalogEntry = { id: SteelStructureId; sectionId: SteelStructureSectionId; sourcePosition: string; sourceText: string; label: string; purposeCategory: PurposeCategory; stressCategory: StressCategory; table51Profiles: Table51Profile[]; mappingQualifier?: string; inferredLoadType?: "static" | "dynamic"; };

export const STEEL_STRUCTURE_SECTIONS: SteelStructureSection[] = [
  { id: "a1-section-01", number: 1, title: "Конструкції кранових колій" },
  { id: "a1-section-02", number: 2, title: "Робочі площадки при наявності рухомого транспорту" },
  { id: "a1-section-03", number: 3, title: "Конструкції технологічних площадок і покриттів" },
  { id: "a1-section-04", number: 4, title: "Колони виробничих споруд і відкритих кранових естакад, стояки робочих і технологічних площадок" },
  { id: "a1-section-05", number: 5, title: "Конструкції покриття" },
  { id: "a1-section-06", number: 6, title: "Конструкції фахверка" },
  { id: "a1-section-07", number: 7, title: "Допоміжні конструкції виробничих споруд" },
  { id: "a1-section-08", number: 8, title: "Транспортерні галереї" },
  { id: "a1-section-09", number: 9, title: "Опори повітряних ліній електропередавання, конструкцій відкритих розподільних пристроїв" },
  { id: "a1-section-10", number: 10, title: "Антенні споруди зв’язку заввишки до 500 м" },
  { id: "a1-section-11", number: 11, title: "Витяжні башти" },
  { id: "a1-section-12", number: 12, title: "Димові труби" },
  { id: "a1-section-13", number: 13, title: "Градирні баштові і вентиляторні, водонапірні башти" },
  { id: "a1-section-14", number: 14, title: "Бункери" },
  { id: "a1-section-15", number: 15, title: "Резервуари і газгольдери" },
  { id: "a1-section-16", number: 16, title: "Конструкції контактної мережі транспорту" },
  { id: "a1-section-17", number: 17, title: "Силоси" },
  { id: "a1-section-18", number: 18, title: "Громадські споруди та споруди заввишки понад 75 м" },
];

export const STEEL_STRUCTURE_CATALOG: SteelStructureCatalogEntry[] = [
  { id: "a1-01-01", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Підкранові балки (крім ребер жорсткості)", label: "Підкранові балки (крім ребер жорсткості)", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-02", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Пояси ферм", label: "Пояси ферм", purposeCategory: "А", stressCategory: "I", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-01-03", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Елементи решіток ферм", label: "Елементи решіток ферм", purposeCategory: "А", stressCategory: "I", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8" },
  { id: "a1-01-04", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Фасонки ферм", label: "Фасонки ферм", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-05", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Гальмові балки", label: "Гальмові балки", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-06", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Гальмові ферми", label: "Гальмові ферми", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8; require calculated truss-element subtype" },
  { id: "a1-01-07", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Деталі кріплення до колон", label: "Деталі кріплення до колон", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-08", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Ребра жорсткості", label: "Ребра жорсткості", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-09", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Зварні балки колій підвісного транспорту", label: "Зварні балки колій підвісного транспорту", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-10", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Прокатні балки під технологічні електричні талі", label: "Прокатні балки під технологічні електричні талі", purposeCategory: "Б", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-11", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Прокатні балки під технологічні кран-балки", label: "Прокатні балки під технологічні кран-балки", purposeCategory: "Б", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-12", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Прокатні балки під ремонтні талі", label: "Прокатні балки під ремонтні талі", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-13", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Прокатні балки під ремонтні кран-балки", label: "Прокатні балки під ремонтні кран-балки", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-14", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Прокатні балки під ручні талі", label: "Прокатні балки під ручні талі", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-15", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Прокатні балки під ручні кран-балки", label: "Прокатні балки під ручні кран-балки", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-16", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Допоміжні горизонтальні ферми", label: "Допоміжні горизонтальні ферми", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8; require calculated truss-element subtype" },
  { id: "a1-01-17", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Вертикальні ферми", label: "Вертикальні ферми", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8; require calculated truss-element subtype" },
  { id: "a1-01-18", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Тупикові упори", label: "Тупикові упори", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-01-19", sectionId: "a1-section-01", sourcePosition: "1", sourceText: "Деталі кріплення рейок", label: "Деталі кріплення рейок", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-02-01", sectionId: "a1-section-02", sourcePosition: "2", sourceText: "Балки при залізничному рухомому складі", label: "Балки при залізничному рухомому складі", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-02-02", sectionId: "a1-section-02", sourcePosition: "2", sourceText: "Балки при автонавантажувачах", label: "Балки при автонавантажувачах", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-02-03", sectionId: "a1-section-02", sourcePosition: "2", sourceText: "Балки при іншому транспорті", label: "Балки при іншому транспорті", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-02-04", sectionId: "a1-section-02", sourcePosition: "2", sourceText: "Металевий настил, включений у сумісну роботу з балками настилу", label: "Металевий настил, включений у сумісну роботу з балками настилу", purposeCategory: "Б", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-02-05", sectionId: "a1-section-02", sourcePosition: "2", sourceText: "Ребра жорсткості балок", label: "Ребра жорсткості балок", purposeCategory: "Б", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-02-06", sectionId: "a1-section-02", sourcePosition: "2", sourceText: "Металевий настил, не включений до сумісної роботи з балками настилу", label: "Металевий настил, не включений до сумісної роботи з балками настилу", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-02-07", sectionId: "a1-section-02", sourcePosition: "2", sourceText: "Ребра жорсткості настилу", label: "Ребра жорсткості настилу", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-03-01", sectionId: "a1-section-03", sourcePosition: "3", sourceText: "Головні балки при динамічному навантаженні", label: "Головні балки при динамічному навантаженні", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default", inferredLoadType: "dynamic" },
  { id: "a1-03-02", sectionId: "a1-section-03", sourcePosition: "3", sourceText: "Ригелі рам при динамічному навантаженні", label: "Ригелі рам при динамічному навантаженні", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default", inferredLoadType: "dynamic" },
  { id: "a1-03-03", sectionId: "a1-section-03", sourcePosition: "3", sourceText: "Головні балки при статичному навантаженні", label: "Головні балки при статичному навантаженні", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p6a"], mappingQualifier: "p6a", inferredLoadType: "static" },
  { id: "a1-03-04", sectionId: "a1-section-03", sourcePosition: "3", sourceText: "Другорядні балки при динамічному навантаженні", label: "Другорядні балки при динамічному навантаженні", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default", inferredLoadType: "dynamic" },
  { id: "a1-03-05", sectionId: "a1-section-03", sourcePosition: "3", sourceText: "Другорядні балки при статичному навантаженні", label: "Другорядні балки при статичному навантаженні", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p6a"], mappingQualifier: "p6a", inferredLoadType: "static" },
  { id: "a1-03-06", sectionId: "a1-section-03", sourcePosition: "3", sourceText: "Металевий настил, включений до сумісної роботи з балками настилу при динамічному навантаженні", label: "Металевий настил, включений до сумісної роботи з балками настилу при динамічному навантаженні", purposeCategory: "Б", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default", inferredLoadType: "dynamic" },
  { id: "a1-03-07", sectionId: "a1-section-03", sourcePosition: "3", sourceText: "Металевий настил, окрім зазначеного в позиції 3д", label: "Металевий настил, окрім зазначеного в позиції 3д", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-03-08", sectionId: "a1-section-03", sourcePosition: "3", sourceText: "Ребра жорсткості балок", label: "Ребра жорсткості балок", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-04-01", sectionId: "a1-section-04", sourcePosition: "4", sourceText: "Основні елементи поперечного перерізу", label: "Основні елементи поперечного перерізу", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p3","p6a","p8"], mappingQualifier: "p3, p6a, p8" },
  { id: "a1-04-02", sectionId: "a1-section-04", sourcePosition: "4", sourceText: "Пояси при наскрізному перерізі", label: "Пояси при наскрізному перерізі", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-04-03", sectionId: "a1-section-04", sourcePosition: "4", sourceText: "Решітки при наскрізному перерізі", label: "Решітки при наскрізному перерізі", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8" },
  { id: "a1-04-04", sectionId: "a1-section-04", sourcePosition: "4", sourceText: "Опорні плити", label: "Опорні плити", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p9","p3"], mappingQualifier: "p9, p3; combination allowed by note 3" },
  { id: "a1-04-05", sectionId: "a1-section-04", sourcePosition: "4", sourceText: "Підкранові траверси колон", label: "Підкранові траверси колон", purposeCategory: "А", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-04-06", sectionId: "a1-section-04", sourcePosition: "4", sourceText: "Вертикальні в’язі між колонами", label: "Вертикальні в’язі між колонами", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-04-07", sectionId: "a1-section-04", sourcePosition: "4", sourceText: "Ребра жорсткості колон", label: "Ребра жорсткості колон", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-04-08", sectionId: "a1-section-04", sourcePosition: "4", sourceText: "Діафрагми колон", label: "Діафрагми колон", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-04-09", sectionId: "a1-section-04", sourcePosition: "4", sourceText: "Елементи решіток двоплощинних в’язей", label: "Елементи решіток двоплощинних в’язей", purposeCategory: "В", stressCategory: "III", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8" },
  { id: "a1-04-10", sectionId: "a1-section-04", sourcePosition: "4", sourceText: "В’язі з напруженням меншим за 0,4Ry", label: "В’язі з напруженням меншим за 0,4Ry", purposeCategory: "В", stressCategory: "III", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-05-01", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Ферми покриття, що підлягають безпосередній дії динамічних навантажень від технологічного чи транспортного устаткування", label: "Ферми покриття, що підлягають безпосередній дії динамічних навантажень від технологічного чи транспортного устаткування", purposeCategory: "А", stressCategory: "I", table51Profiles: ["p4","p7","p8"], mappingQualifier: "p4, p7, p8; require calculated truss-element subtype", inferredLoadType: "dynamic" },
  { id: "a1-05-02", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Ригелі покриття, що підлягають безпосередній дії динамічних навантажень від технологічного чи транспортного устаткування", label: "Ригелі покриття, що підлягають безпосередній дії динамічних навантажень від технологічного чи транспортного устаткування", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default", inferredLoadType: "dynamic" },
  { id: "a1-05-03", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Інші елементи покриття, що підлягають безпосередній дії динамічних навантажень від технологічного чи транспортного устаткування", label: "Інші елементи покриття, що підлягають безпосередній дії динамічних навантажень від технологічного чи транспортного устаткування", purposeCategory: "А", stressCategory: "I", table51Profiles: ["p4","p7","p8"], mappingQualifier: "p4, p7, p8 when the selected subtype matches", inferredLoadType: "dynamic" },
  { id: "a1-05-04", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Ферми покриття при статичному навантаженні", label: "Ферми покриття при статичному навантаженні", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p4","p6b","p7","p8"], mappingQualifier: "p4, p6b, p7, p8; require calculated truss-element subtype", inferredLoadType: "static" },
  { id: "a1-05-05", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Ригелі покриття при статичному навантаженні", label: "Ригелі покриття при статичному навантаженні", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p6a"], mappingQualifier: "p6a", inferredLoadType: "static" },
  { id: "a1-05-06", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Інші елементи покриття при статичному навантаженні", label: "Інші елементи покриття при статичному навантаженні", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p4","p6b","p7","p8"], mappingQualifier: "p4, p6b, p7, p8 when the selected subtype matches", inferredLoadType: "static" },
  { id: "a1-05-07", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Вузлові фасонки елементів покрівлі", label: "Вузлові фасонки елементів покрівлі", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-05-08", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Ліхтарні панелі", label: "Ліхтарні панелі", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-05-09", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Панелі покрівлі", label: "Панелі покрівлі", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-05-10", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Прогони покрівлі", label: "Прогони покрівлі", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-05-11", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Горизонтальні торцеві в’язі в рівні покрівлі", label: "Горизонтальні торцеві в’язі в рівні покрівлі", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-05-12", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Поздовжні в’язі при кроці колон, більшому за крок кроквяних ферм", label: "Поздовжні в’язі при кроці колон, більшому за крок кроквяних ферм", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-05-13", sectionId: "a1-section-05", sourcePosition: "5", sourceText: "Інші в’язі покрівлі", label: "Інші в’язі покрівлі", purposeCategory: "В", stressCategory: "III", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-06-01", sectionId: "a1-section-06", sourcePosition: "6", sourceText: "Ригелі під цегляні стіни", label: "Ригелі під цегляні стіни", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-06-02", sectionId: "a1-section-06", sourcePosition: "6", sourceText: "Ригелі над воротами", label: "Ригелі над воротами", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-06-03", sectionId: "a1-section-06", sourcePosition: "6", sourceText: "Стояки", label: "Стояки", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p6a","p8"], mappingQualifier: "p6a, p8" },
  { id: "a1-06-04", sectionId: "a1-section-06", sourcePosition: "6", sourceText: "Торцеві ферми", label: "Торцеві ферми", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8; require calculated truss-element subtype" },
  { id: "a1-06-05", sectionId: "a1-section-06", sourcePosition: "6", sourceText: "Вітрові ферми", label: "Вітрові ферми", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8; require calculated truss-element subtype" },
  { id: "a1-06-06", sectionId: "a1-section-06", sourcePosition: "6", sourceText: "Ригелі, крім зазначених у позиції 6а", label: "Ригелі, крім зазначених у позиції 6а", purposeCategory: "В", stressCategory: "III", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-06-07", sectionId: "a1-section-06", sourcePosition: "6", sourceText: "Інші елементи фахверка", label: "Інші елементи фахверка", purposeCategory: "В", stressCategory: "III", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-07-01", sectionId: "a1-section-07", sourcePosition: "7", sourceText: "Косоури сходів", label: "Косоури сходів", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-07-02", sectionId: "a1-section-07", sourcePosition: "7", sourceText: "Сходи виробничих споруд", label: "Сходи виробничих споруд", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-07-03", sectionId: "a1-section-07", sourcePosition: "7", sourceText: "Перехідні площадки виробничих споруд", label: "Перехідні площадки виробничих споруд", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-07-04", sectionId: "a1-section-07", sourcePosition: "7", sourceText: "Огородження виробничих споруд", label: "Огородження виробничих споруд", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-07-05", sectionId: "a1-section-07", sourcePosition: "7", sourceText: "Площадки світильників", label: "Площадки світильників", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-07-06", sectionId: "a1-section-07", sourcePosition: "7", sourceText: "Посадкові площадки на крани", label: "Посадкові площадки на крани", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-07-07", sectionId: "a1-section-07", sourcePosition: "7", sourceText: "Балки підвісних стель", label: "Балки підвісних стель", purposeCategory: "В", stressCategory: "III", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-07-08", sectionId: "a1-section-07", sourcePosition: "7", sourceText: "Імпости", label: "Імпости", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-07-09", sectionId: "a1-section-07", sourcePosition: "7", sourceText: "Віконні рами", label: "Віконні рами", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-07-10", sectionId: "a1-section-07", sourcePosition: "7", sourceText: "Ліхтарні рами", label: "Ліхтарні рами", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-08-01", sectionId: "a1-section-08", sourcePosition: "8", sourceText: "Прогінні споруди транспортерних галерей", label: "Прогінні споруди транспортерних галерей", purposeCategory: "А", stressCategory: "I", table51Profiles: ["p6b","p7","p8"], mappingQualifier: "p6b, p7, p8; require calculated element subtype" },
  { id: "a1-08-02", sectionId: "a1-section-08", sourcePosition: "8", sourceText: "Несучі балки під конвеєри", label: "Несучі балки під конвеєри", purposeCategory: "А", stressCategory: "I", table51Profiles: ["p6a"], mappingQualifier: "p6a when load is static" },
  { id: "a1-08-03", sectionId: "a1-section-08", sourcePosition: "8", sourceText: "Фасонки ферм транспортерних галерей", label: "Фасонки ферм транспортерних галерей", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-08-04", sectionId: "a1-section-08", sourcePosition: "8", sourceText: "Опори транспортерних галерей", label: "Опори транспортерних галерей", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p6a","p8"], mappingQualifier: "p6a, p8" },
  { id: "a1-08-05", sectionId: "a1-section-08", sourcePosition: "8", sourceText: "В’язі між колонами транспортерних галерей", label: "В’язі між колонами транспортерних галерей", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-08-06", sectionId: "a1-section-08", sourcePosition: "8", sourceText: "Опорні ребра балок транспортерних галерей", label: "Опорні ребра балок транспортерних галерей", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-08-07", sectionId: "a1-section-08", sourcePosition: "8", sourceText: "Елементи фахверка прогінних споруд", label: "Елементи фахверка прогінних споруд", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-08-08", sectionId: "a1-section-08", sourcePosition: "8", sourceText: "В’язі прогінних споруд", label: "В’язі прогінних споруд", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-08-09", sectionId: "a1-section-08", sourcePosition: "8", sourceText: "Прогони покриттів прогінних споруд", label: "Прогони покриттів прогінних споруд", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-08-10", sectionId: "a1-section-08", sourcePosition: "8", sourceText: "Балки покриттів прогінних споруд", label: "Балки покриттів прогінних споруд", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-08-11", sectionId: "a1-section-08", sourcePosition: "8", sourceText: "Ребра жорсткості балок прогінних споруд", label: "Ребра жорсткості балок прогінних споруд", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-09-01", sectionId: "a1-section-09", sourcePosition: "9", sourceText: "Зварні спеціальні опори великих переходів заввишки понад 60 м", label: "Зварні спеціальні опори великих переходів заввишки понад 60 м", purposeCategory: "А", stressCategory: "I", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8" },
  { id: "a1-09-02", sectionId: "a1-section-09", sourcePosition: "9", sourceText: "Опори повітряних ліній електропередавання, крім спеціальних опор великих переходів заввишки понад 60 м", label: "Опори повітряних ліній електропередавання, крім спеціальних опор великих переходів заввишки понад 60 м", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8" },
  { id: "a1-09-03", sectionId: "a1-section-09", sourcePosition: "9", sourceText: "Опори під вимикачі відкритих розподільних пристроїв", label: "Опори під вимикачі відкритих розподільних пристроїв", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p6a","p7","p8"], mappingQualifier: "p6a, p7, p8" },
  { id: "a1-09-04", sectionId: "a1-section-09", sourcePosition: "9", sourceText: "Портали під ошинування відкритих розподільних пристроїв", label: "Портали під ошинування відкритих розподільних пристроїв", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p6a","p7","p8"], mappingQualifier: "p6a, p7, p8" },
  { id: "a1-09-05", sectionId: "a1-section-09", sourcePosition: "9", sourceText: "Опори під устаткування відкритих розподільних пристроїв, крім зазначених у позиціях 9а і 9б", label: "Опори під устаткування відкритих розподільних пристроїв, крім зазначених у позиціях 9а і 9б", purposeCategory: "В", stressCategory: "II", table51Profiles: ["p6a","p7","p8"], mappingQualifier: "p6a, p7, p8" },
  { id: "a1-10-01", sectionId: "a1-section-10", sourcePosition: "10", sourceText: "Стовбури щогл", label: "Стовбури щогл", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8; require calculated element subtype" },
  { id: "a1-10-02", sectionId: "a1-section-10", sourcePosition: "10", sourceText: "Стовбури башт", label: "Стовбури башт", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8; require calculated element subtype" },
  { id: "a1-10-03", sectionId: "a1-section-10", sourcePosition: "10", sourceText: "Решітки антенних споруд", label: "Решітки антенних споруд", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8" },
  { id: "a1-10-04", sectionId: "a1-section-10", sourcePosition: "10", sourceText: "Елементи обпирання антенних споруд на фундаменти", label: "Елементи обпирання антенних споруд на фундаменти", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p9"], mappingQualifier: "p9 when the element is a support plate" },
  { id: "a1-10-05", sectionId: "a1-section-10", sourcePosition: "10", sourceText: "Механічні деталі відтяжок щогл", label: "Механічні деталі відтяжок щогл", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-10-06", sectionId: "a1-section-10", sourcePosition: "10", sourceText: "Механічні деталі антенних полотен", label: "Механічні деталі антенних полотен", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-10-07", sectionId: "a1-section-10", sourcePosition: "10", sourceText: "Деталі кріплення відтяжок до фундаментів", label: "Деталі кріплення відтяжок до фундаментів", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-10-08", sectionId: "a1-section-10", sourcePosition: "10", sourceText: "Деталі кріплення відтяжок до стовбурів сталевих опор", label: "Деталі кріплення відтяжок до стовбурів сталевих опор", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-10-09", sectionId: "a1-section-10", sourcePosition: "10", sourceText: "Діафрагми баштових опор", label: "Діафрагми баштових опор", purposeCategory: "Б", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-10-10", sectionId: "a1-section-10", sourcePosition: "10", sourceText: "Хідники антенних споруд", label: "Хідники антенних споруд", purposeCategory: "Б", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-10-11", sectionId: "a1-section-10", sourcePosition: "10", sourceText: "Перехідні площадки антенних споруд", label: "Перехідні площадки антенних споруд", purposeCategory: "Б", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-11-01", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Пояси витяжних башт", label: "Пояси витяжних башт", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-11-02", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Вузлові фасонки витяжних башт", label: "Вузлові фасонки витяжних башт", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-11-03", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Газовідвідний стовбур", label: "Газовідвідний стовбур", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-11-04", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Елементи решітки витяжних башт", label: "Елементи решітки витяжних башт", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8" },
  { id: "a1-11-05", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Балки діафрагм, що безпосередньо сприймають вагу стовбура", label: "Балки діафрагм, що безпосередньо сприймають вагу стовбура", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-11-06", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Площадки діафрагм, що безпосередньо сприймають вагу стовбура", label: "Площадки діафрагм, що безпосередньо сприймають вагу стовбура", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-11-07", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Опорні плити витяжних башт", label: "Опорні плити витяжних башт", purposeCategory: "В", stressCategory: "III", table51Profiles: ["p9"], mappingQualifier: "p9" },
  { id: "a1-11-08", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Хідники витяжних башт", label: "Хідники витяжних башт", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-11-09", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Огородження витяжних башт", label: "Огородження витяжних башт", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-11-10", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Настил площадок витяжних башт", label: "Настил площадок витяжних башт", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-11-11", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Балки діафрагм, що не сприймають вагу стовбура", label: "Балки діафрагм, що не сприймають вагу стовбура", purposeCategory: "В", stressCategory: "III", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-11-12", sectionId: "a1-section-11", sourcePosition: "11", sourceText: "Площадки діафрагм, що не сприймають вагу стовбура", label: "Площадки діафрагм, що не сприймають вагу стовбура", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-12-01", sectionId: "a1-section-12", sourcePosition: "12", sourceText: "Сталева оболонка димової труби", label: "Сталева оболонка димової труби", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-12-02", sectionId: "a1-section-12", sourcePosition: "12", sourceText: "Ребра жорсткості димової труби", label: "Ребра жорсткості димової труби", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-12-03", sectionId: "a1-section-12", sourcePosition: "12", sourceText: "Площадки димової труби", label: "Площадки димової труби", purposeCategory: "Б", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-12-04", sectionId: "a1-section-12", sourcePosition: "12", sourceText: "Опорні кільця димової труби", label: "Опорні кільця димової труби", purposeCategory: "Б", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-12-05", sectionId: "a1-section-12", sourcePosition: "12", sourceText: "Хідники димової труби", label: "Хідники димової труби", purposeCategory: "Б", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-12-06", sectionId: "a1-section-12", sourcePosition: "12", sourceText: "Огородження димової труби", label: "Огородження димової труби", purposeCategory: "Б", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-13-01", sectionId: "a1-section-13", sourcePosition: "13", sourceText: "Пояси решітчастих башт", label: "Пояси решітчастих башт", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p2","p8"], mappingQualifier: "p2 when part of a water-tower support, p8" },
  { id: "a1-13-02", sectionId: "a1-section-13", sourcePosition: "13", sourceText: "Кільця жорсткості башт", label: "Кільця жорсткості башт", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p2"], mappingQualifier: "p2 when part of a water-tower support" },
  { id: "a1-13-03", sectionId: "a1-section-13", sourcePosition: "13", sourceText: "Решітки башт", label: "Решітки башт", purposeCategory: "А", stressCategory: "III", table51Profiles: ["p2","p7","p8"], mappingQualifier: "p2 when part of a water-tower support, p7, p8" },
  { id: "a1-13-04", sectionId: "a1-section-13", sourcePosition: "13", sourceText: "Вузлові фасонки башт", label: "Вузлові фасонки башт", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p2"], mappingQualifier: "p2 when part of a water-tower support" },
  { id: "a1-13-05", sectionId: "a1-section-13", sourcePosition: "13", sourceText: "Фахверк градирень і водонапірних башт", label: "Фахверк градирень і водонапірних башт", purposeCategory: "В", stressCategory: "III", table51Profiles: ["p8"], mappingQualifier: "p8" },
  { id: "a1-13-06", sectionId: "a1-section-13", sourcePosition: "13", sourceText: "Допоміжні площадки градирень і водонапірних башт", label: "Допоміжні площадки градирень і водонапірних башт", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-13-07", sectionId: "a1-section-13", sourcePosition: "13", sourceText: "Обшивки градирень", label: "Обшивки градирень", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-14-01", sectionId: "a1-section-14", sourcePosition: "14", sourceText: "Бункерні балки", label: "Бункерні балки", purposeCategory: "А", stressCategory: "I", table51Profiles: ["p6a"], mappingQualifier: "p6a when load is static" },
  { id: "a1-14-02", sectionId: "a1-section-14", sourcePosition: "14", sourceText: "Оболонки параболічних бункерів", label: "Оболонки параболічних бункерів", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-14-03", sectionId: "a1-section-14", sourcePosition: "14", sourceText: "Стінки інших бункерів", label: "Стінки інших бункерів", purposeCategory: "А", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-14-04", sectionId: "a1-section-14", sourcePosition: "14", sourceText: "Ребра жорсткості бункерів", label: "Ребра жорсткості бункерів", purposeCategory: "А", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-15-01", sectionId: "a1-section-15", sourcePosition: "15", sourceText: "Стінки резервуарів місткістю 10 тис. м³ і більше", label: "Стінки резервуарів місткістю 10 тис. м³ і більше", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-15-02", sectionId: "a1-section-15", sourcePosition: "15", sourceText: "Кромки днищ резервуарів місткістю 10 тис. м³ і більше", label: "Кромки днищ резервуарів місткістю 10 тис. м³ і більше", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-15-03", sectionId: "a1-section-15", sourcePosition: "15", sourceText: "Фасонки покриттів резервуарів місткістю 10 тис. м³ і більше", label: "Фасонки покриттів резервуарів місткістю 10 тис. м³ і більше", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-15-04", sectionId: "a1-section-15", sourcePosition: "15", sourceText: "Стінки резервуарів місткістю менше ніж 10 тис. м³", label: "Стінки резервуарів місткістю менше ніж 10 тис. м³", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-15-05", sectionId: "a1-section-15", sourcePosition: "15", sourceText: "Кромки днищ резервуарів місткістю менше ніж 10 тис. м³", label: "Кромки днищ резервуарів місткістю менше ніж 10 тис. м³", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-15-06", sectionId: "a1-section-15", sourcePosition: "15", sourceText: "Центральні частини днищ резервуарів", label: "Центральні частини днищ резервуарів", purposeCategory: "А", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-15-07", sectionId: "a1-section-15", sourcePosition: "15", sourceText: "Опорні кільця покриття резервуарів", label: "Опорні кільця покриття резервуарів", purposeCategory: "А", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-15-08", sectionId: "a1-section-15", sourcePosition: "15", sourceText: "Кільця жорсткості резервуарів", label: "Кільця жорсткості резервуарів", purposeCategory: "А", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-15-09", sectionId: "a1-section-15", sourcePosition: "15", sourceText: "Плавучі покрівлі резервуарів", label: "Плавучі покрівлі резервуарів", purposeCategory: "А", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-15-10", sectionId: "a1-section-15", sourcePosition: "15", sourceText: "Понтони покриття резервуарів", label: "Понтони покриття резервуарів", purposeCategory: "А", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-15-11", sectionId: "a1-section-15", sourcePosition: "15", sourceText: "Внутрішні корпуси ізотермічних резервуарів при температурі зберігання не вище −50 °C", label: "Внутрішні корпуси ізотермічних резервуарів при температурі зберігання не вище −50 °C", purposeCategory: "А", stressCategory: "I", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-16-01", sectionId: "a1-section-16", sourcePosition: "16", sourceText: "Тяги, пов’язані з натягом проводів", label: "Тяги, пов’язані з натягом проводів", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p5"], mappingQualifier: "p5" },
  { id: "a1-16-02", sectionId: "a1-section-16", sourcePosition: "16", sourceText: "Штанги, пов’язані з натягом проводів", label: "Штанги, пов’язані з натягом проводів", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-16-03", sectionId: "a1-section-16", sourcePosition: "16", sourceText: "Хомути, пов’язані з натягом проводів", label: "Хомути, пов’язані з натягом проводів", purposeCategory: "А", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-16-04", sectionId: "a1-section-16", sourcePosition: "16", sourceText: "Опори несучих, підтримувальних і фіксувальних пристроїв", label: "Опори несучих, підтримувальних і фіксувальних пристроїв", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p6a","p7","p8"], mappingQualifier: "p6a, p7, p8" },
  { id: "a1-16-05", sectionId: "a1-section-16", sourcePosition: "16", sourceText: "Ригелі жорстких поперечин", label: "Ригелі жорстких поперечин", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-16-06", sectionId: "a1-section-16", sourcePosition: "16", sourceText: "Прожекторні щогли", label: "Прожекторні щогли", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["p7","p8"], mappingQualifier: "p7, p8; require calculated element subtype" },
  { id: "a1-16-07", sectionId: "a1-section-16", sourcePosition: "16", sourceText: "Фіксатори контактної мережі", label: "Фіксатори контактної мережі", purposeCategory: "Б", stressCategory: "II", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-16-08", sectionId: "a1-section-16", sourcePosition: "16", sourceText: "Допоміжні конструкції контактної мережі", label: "Допоміжні конструкції контактної мережі", purposeCategory: "В", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-17-01", sectionId: "a1-section-17", sourcePosition: "17", sourceText: "Оболонки силосів", label: "Оболонки силосів", purposeCategory: "А", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-17-02", sectionId: "a1-section-17", sourcePosition: "17", sourceText: "Ребра жорсткості силосів", label: "Ребра жорсткості силосів", purposeCategory: "А", stressCategory: "III", table51Profiles: ["default"], mappingQualifier: "default" },
  { id: "a1-18-01", sectionId: "a1-section-18", sourcePosition: "18", sourceText: "Перекриття", label: "Перекриття", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p1"], mappingQualifier: "p1 after element subtype and load checks" },
  { id: "a1-18-02", sectionId: "a1-section-18", sourcePosition: "18", sourceText: "Покриття", label: "Покриття", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p4","p6b","p7","p8"], mappingQualifier: "p4, p6b, p7, p8 after calculated element subtype" },
  { id: "a1-18-03", sectionId: "a1-section-18", sourcePosition: "18", sourceText: "Косоури сходів", label: "Косоури сходів", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p6a"], mappingQualifier: "p6a" },
  { id: "a1-18-04", sectionId: "a1-section-18", sourcePosition: "18", sourceText: "Колони", label: "Колони", purposeCategory: "А", stressCategory: "II", table51Profiles: ["p2","p6a"], mappingQualifier: "p2 for a public building, p6a" },
];

export const STEEL_STRENGTH_CLASSES = [
  "С235",
  "С245",
  "С255",
  "С275",
  "С295",
  "С325",
  "С345",
  "С345К",
  "С355",
  "С375",
  "С390",
  "С390К",
  "С420",
  "С440",
  "С460",
  "С500",
  "С550",
  "С590",
  "С620",
  "С690",
] as const;
export type SteelStrengthClass = (typeof STEEL_STRENGTH_CLASSES)[number];
const ALL_PRODUCT_TYPES: ProductType[] = ["section", "long", "sheet", "universal_plate", "cold_formed"];
export type SteelGradeStandardOption = { id: string; steelClass: SteelStrengthClass; label: string; productTypes: ProductType[]; gammaM: number; minThicknessMm?: number; maxThicknessMm?: number };
export const STEEL_GRADE_STANDARD_OPTIONS: SteelGradeStandardOption[] = [
  { id: "c235-01", steelClass: "С235", label: "С235 — ДСТУ 8539", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.025 },
  { id: "c235-02", steelClass: "С235", label: "Ст3кп2 — ДСТУ 2651/ГОСТ 380; ДСТУ 4484/ГОСТ 535; ДСТУ 8803", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c235-03", steelClass: "С235", label: "S235JR, S235J0, S235J2 — ДСТУ EN 10025-2:2007", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c235-04", steelClass: "С235", label: "S235JRH — ДСТУ EN 10219-1", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c245-01", steelClass: "С245", label: "С245 — ДСТУ 8539", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.025 },
  { id: "c245-02", steelClass: "С245", label: "Ст3пс5 (листовий — до 20 мм; фасонний — до 40 мм) — ДСТУ 2651/ГОСТ 380; ДСТУ 4484/ГОСТ 535; ДСТУ 8803", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c255-01", steelClass: "С255", label: "С255 — ДСТУ 8539", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.025 },
  { id: "c255-02", steelClass: "С255", label: "Ст3сп5 (листовий — понад 4 мм; фасонний — до 10 мм) — ДСТУ 2651/ГОСТ 380; ДСТУ 4484/ГОСТ 535; ДСТУ 8803", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c255-03", steelClass: "С255", label: "Ст3Гпс5 (листовий — понад 4 мм) — ДСТУ 2651/ГОСТ 380; ДСТУ 4484/ГОСТ 535; ДСТУ 8803", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c255-04", steelClass: "С255", label: "Ст3Гсп5 (листовий — до 40 мм) — ДСТУ 2651/ГОСТ 380; ДСТУ 4484/ГОСТ 535; ДСТУ 8803", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c275-01", steelClass: "С275", label: "S275JR, S275J0, S275J2 — ДСТУ EN 10025-2", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c275-02", steelClass: "С275", label: "S275N, S275NL — ДСТУ EN 10025-3", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c275-03", steelClass: "С275", label: "S275M, S275ML — ДСТУ EN 10025-4", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c275-04", steelClass: "С275", label: "S275J0H, S275J2H, S275NH, S275NLH, S275MH, S275MLH — ДСТУ EN 10219-1", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c295-01", steelClass: "С295", label: "09Г2 (листовий та фасонний — до 32 мм) — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c295-02", steelClass: "С295", label: "09Г2С (листовий та фасонний — до 32 мм) — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c325-01", steelClass: "С325", label: "09Г2С (листовий та фасонний — понад 10 мм до 20 мм включно) — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c325-02", steelClass: "С325", label: "14Г2 (листовий та фасонний — до 32 мм включно) — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c325-03", steelClass: "С325", label: "15ХСНД (фасонний — понад 20 мм до 32 мм) — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c345-01", steelClass: "С345", label: "С345 — ДСТУ 8539", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.025 },
  { id: "c345-02", steelClass: "С345", label: "09Г2С (листовий та фасонний — до 10 мм включно) — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c345-03", steelClass: "С345", label: "15ХСНД (листовий — до 32 мм; фасонний — до 20 мм включно) — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c345к-01", steelClass: "С345К", label: "С345К — ДСТУ 8539", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.025 },
  { id: "c345к-02", steelClass: "С345К", label: "10ХНДП — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c355-01", steelClass: "С355", label: "S355J2, S355K2 — ДСТУ EN 10025-2", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c355-02", steelClass: "С355", label: "S355N, S355NL — ДСТУ EN 10025-3", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c355-03", steelClass: "С355", label: "S355M, S355ML — ДСТУ EN 10025-4", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c355-04", steelClass: "С355", label: "S355J0H, S355J2H, S355K2H, S355NH, S355NLH, S355MH, S355MLH — ДСТУ EN 10219-1", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c375-01", steelClass: "С375", label: "С375 — ДСТУ 8539", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.025 },
  { id: "c390-01", steelClass: "С390", label: "С390, С390-1 — ДСТУ 8539", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.025 },
  { id: "c390-02", steelClass: "С390", label: "14Г2АФ — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c390-03", steelClass: "С390", label: "15Г2СФ — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c390-04", steelClass: "С390", label: "10ХСНД (листовий — до 40 мм; фасонний — без обмежень) — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c390к-01", steelClass: "С390К", label: "15Г2АФДпс (С390К) — ДСТУ 8541", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c420-01", steelClass: "С420", label: "S420N, S420NL — ДСТУ EN 10025-3", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c420-02", steelClass: "С420", label: "S420M, S420ML — ДСТУ EN 10025-4", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c420-03", steelClass: "С420", label: "S420MH, S420MLH — ДСТУ EN 10219-1", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c440-01", steelClass: "С440", label: "С440 — ДСТУ 8539", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.025 },
  { id: "c460-01", steelClass: "С460", label: "S460N, S460NL — ДСТУ EN 10025-3", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c460-02", steelClass: "С460", label: "S460M, S460ML — ДСТУ EN 10025-4", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c460-03", steelClass: "С460", label: "S460NH, S460NLH, S460MH, S460MLH — ДСТУ EN 10219-1", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c500-01", steelClass: "С500", label: "S500Q, S500QL — ДСТУ EN 10025-6", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c550-01", steelClass: "С550", label: "С550 — ДСТУ 8539", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.025 },
  { id: "c550-02", steelClass: "С550", label: "S550Q, S550QL, S550QL1 — ДСТУ EN 10025-6", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c590-01", steelClass: "С590", label: "С590 — ДСТУ 8539", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.1 },
  { id: "c620-01", steelClass: "С620", label: "S620Q, S620QL — ДСТУ EN 10025-6", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
  { id: "c690-01", steelClass: "С690", label: "S690Q, S690QL, S690QL1 — ДСТУ EN 10025-6", productTypes: ALL_PRODUCT_TYPES, gammaM: 1.05 },
];
export type TableG1Cell = "+" | "-" | "+a" | "+b" | "blank";
export const TABLE_G1_MATRIX: Record<SteelStrengthClass, [TableG1Cell, TableG1Cell, TableG1Cell, TableG1Cell]> = {
  "С235": ["-","-","+a","+"],
  "С245": ["-","+b","+","-"],
  "С255": ["+","+","+","-"],
  "С275": ["-","+b","+","-"],
  "С295": ["+","+","+","-"],
  "С325": ["+","+","+","-"],
  "С345": ["+","+","+","-"],
  "С345К": ["blank","blank","+","blank"],
  "С355": ["+","+","+","-"],
  "С375": ["+","+","+","-"],
  "С390": ["+","+","+","-"],
  "С390К": ["+","+","+","-"],
  "С420": ["+","+","+","-"],
  "С440": ["+","+","+","-"],
  "С460": ["+","+","+","-"],
  "С500": ["+","+","+","-"],
  "С550": ["+","+","+","+"],
  "С590": ["-","+","+","-"],
  "С620": ["+","+","+","-"],
  "С690": ["+","+","+","+"],
};
export function getSteelStructureEntry(id: string) { return STEEL_STRUCTURE_CATALOG.find((entry) => entry.id === id); }
export function getSteelStructuresForSection(sectionId: SteelStructureSectionId) { return STEEL_STRUCTURE_CATALOG.filter((entry) => entry.sectionId === sectionId); }
function productWords(productType: ProductType) {
  return productType === "sheet" || productType === "universal_plate"
    ? ["листовий"]
    : productType === "section" || productType === "long"
      ? ["фасонний"]
      : [];
}

export function steelGradeSupportsProductAndThickness(
  option: SteelGradeStandardOption,
  productType: ProductType,
  thicknessMm?: number,
) {
  if (option.label.includes("ДСТУ EN 10219-1")) return productType === "cold_formed";

  const hasSheet = option.label.includes("листовий");
  const hasSection = option.label.includes("фасонний");
  if (hasSheet || hasSection) {
    const words = productWords(productType);
    if (words.length === 0) return false;
    const word = words[0];
    if (!option.label.includes(word)) return false;
    if (thicknessMm === undefined) return true;
    const match = option.label.match(new RegExp(`${word}\\s*[—-]\\s*([^;)]+)`));
    const rule = match?.[1] ?? "";
    const range = rule.match(/понад\s*(\d+(?:[.,]\d+)?)\s*мм\s*до\s*(\d+(?:[.,]\d+)?)/);
    if (range) return thicknessMm > Number(range[1].replace(",", ".")) && thicknessMm <= Number(range[2].replace(",", "."));
    const max = rule.match(/до\s*(\d+(?:[.,]\d+)?)/);
    if (max && thicknessMm > Number(max[1].replace(",", "."))) return false;
    const min = rule.match(/понад\s*(\d+(?:[.,]\d+)?)/);
    if (min && thicknessMm <= Number(min[1].replace(",", "."))) return false;
  }
  return option.productTypes.includes(productType);
}

export function getSteelGradeOptions(steelClass: SteelStrengthClass, productType: ProductType) {
  return STEEL_GRADE_STANDARD_OPTIONS.filter(
    (option) => option.steelClass === steelClass && steelGradeSupportsProductAndThickness(option, productType),
  );
}
